### PR TITLE
fix pagination (close #62)

### LINKED ISSUE #62: Arreglar paginación

### PR DESCRIPTION
**Pull request by JuJoDevs**
🎩 How was this resolved?

Cambios Realizados:
Implementación de Paging Compose

Detalles Adicionales:
https://developersbreach.com/paging-compose-android/
https://developer.android.com/jetpack/androidx/releases/paging

Instrucciones para Revisión:

Otros Cambios:

### CODE REVIEW

File: app/src/main/kotlin/com/architects/pokearch/ui/components/extensions/LazyGridScopeExtensions.kt [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+import android.annotation.SuppressLint
+import android.os.Parcel
+import android.os.Parcelable
+import androidx.compose.foundation.lazy.grid.LazyGridItemScope
+import androidx.compose.foundation.lazy.grid.LazyGridScope
+import androidx.compose.runtime.Composable
+import androidx.paging.compose.LazyPagingItems
+
+fun <T : Any> LazyGridScope.itemsPaging(
```
Comment (timacosta) [inline app/src/main/kotlin/com/architects/pokearch/ui/components/extensions/LazyGridScopeExtensions.kt:11]: Estaba leyendo que esto ya esta integrado en paging compose tmb para LazyVerticalGrid: https://developer.android.com/jetpack/androidx/releases/paging#paging-compose-3.2.1

Support for all lazy layouts such as LazyVerticalGrid and HorizontalPager as well as custom lazy components from Wear and TV libraries. This was achieved through new lower level LazyPagingItems extension methods itemKey and itemContentType, which helps you implement the key and contentType parameters to the standard items APIs that already exist for LazyColumn, LazyVerticalGrid as well as their equivalents in APIs like HorizontalPager.

```
LazyVerticalGrid(
        state = lazyGridState,
        columns = GridCells.Adaptive(dimensionResource(id = R.dimen.grid_cell_min_size))
    ) {
        items(pokemons.itemCount) {
            pokemons[it]?.let { pokemon ->
                HomeItem(
                    pokemon = pokemon,
                    onItemClick = { pokemonId ->
                        onItemClick(pokemonId)
                    }
                )
            }
        }
```

Esto tmb valdría creo. No lo he probado a fondo, pero en teoría toda esta parte copiada del framework no haría falta. Pero vamos, que tmb funciona todo.

**Review by timacosta — APPROVED** [review]

**Review by Mj-br — APPROVED** [review]
